use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use crate::{
    obc_boundary_output_path, read_obc_order_netcdf, validate_unstructured_mesh, UnstructuredMesh,
};

/// Evidence report from writing `MOD_file_preprocess.F90:FVCOM_Mesh_Save` output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FvcomMesh2dmWriteReport {
    pub output: PathBuf,
    pub triangles: usize,
    pub nodes: usize,
    pub boundary_segments: usize,
}

/// Compatibility output path for `MOD_file_preprocess.F90:FVCOM_Mesh_Save`.
pub fn fvcom_mesh_2dm_output_path(file_dir: impl AsRef<Path>) -> PathBuf {
    file_dir.as_ref().join("result/fvcom.2dm")
}

/// Write the SMS/FVCOM `.2dm` mesh generated by
/// `MOD_file_preprocess.F90:FVCOM_Mesh_Save`.
pub fn write_fvcom_mesh_2dm(
    output: impl AsRef<Path>,
    mesh: &UnstructuredMesh,
    obc_order: &[usize],
) -> io::Result<FvcomMesh2dmWriteReport> {
    validate_unstructured_mesh(mesh)?;
    validate_fvcom_mesh_2dm_connectivity(mesh)?;

    let output = output.as_ref();
    crate::ensure_parent_dir(output)?;

    let mut file = fs::File::create(output)?;
    writeln!(file, "MESH2D")?;
    writeln!(file, "MESHNAME \"FVCOM Mesh\"")?;

    for (idx, vertices) in mesh.m_to_w.iter().enumerate().skip(1) {
        writeln!(
            file,
            "E3T {} {} {} {} 1",
            idx,
            vertices[0] - 1,
            vertices[1] - 1,
            vertices[2] - 1
        )?;
    }

    for (idx, point) in mesh.w_points.iter().enumerate().skip(1) {
        writeln!(
            file,
            "ND {} {:.6} {:.6} {:.6}",
            idx, point.lon, point.lat, 0.0_f64
        )?;
    }

    let boundary_segments = write_fvcom_ns_records(&mut file, obc_order)?;

    Ok(FvcomMesh2dmWriteReport {
        output: output.to_path_buf(),
        triangles: mesh.m_to_w.len().saturating_sub(1),
        nodes: mesh.w_points.len().saturating_sub(1),
        boundary_segments,
    })
}

/// File-level wrapper for `MOD_file_preprocess.F90:FVCOM_Mesh_Save`.
pub fn write_fvcom_mesh_save_outputs(
    file_dir: impl AsRef<Path>,
    mesh: &UnstructuredMesh,
    mask_patch_on: bool,
) -> io::Result<FvcomMesh2dmWriteReport> {
    let file_dir = file_dir.as_ref();
    let obc_order = read_obc_order_netcdf(obc_boundary_output_path(file_dir, mask_patch_on))?;
    write_fvcom_mesh_2dm(fvcom_mesh_2dm_output_path(file_dir), mesh, &obc_order)
}

fn validate_fvcom_mesh_2dm_connectivity(mesh: &UnstructuredMesh) -> io::Result<()> {
    if mesh.m_points.is_empty() || mesh.w_points.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "FVCOM .2dm writer expects Canonical-indexed mesh placeholders",
        ));
    }
    let max_vertex = i32::try_from(mesh.w_points.len() - 1).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "FVCOM .2dm writer vertex count exceeds i32 connectivity range",
        )
    })?;
    for (triangle, vertices) in mesh.m_to_w.iter().enumerate().skip(1) {
        for &vertex in vertices {
            if vertex < 2 || vertex > max_vertex + 1 {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!(
                        "triangle {triangle} canonicals vertex {vertex}, expected Canonical index 2..{}",
                        max_vertex + 1
                    ),
                ));
            }
        }
    }
    Ok(())
}

pub(crate) fn write_fvcom_ns_records(
    file: &mut fs::File,
    obc_order: &[usize],
) -> io::Result<usize> {
    if obc_order.is_empty() {
        return Ok(0);
    }

    let mut order = obc_order.to_vec();
    if order.last().copied() != Some(1) {
        order.push(1);
    }

    let mut boundary_segments = 0_usize;
    let mut position_in_record = 0_usize;
    for idx in 1..order.len().saturating_sub(1) {
        let current = order[idx];
        if current == 1 {
            continue;
        }
        if current == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "obc_order contains zero boundary vertex id",
            ));
        }
        if position_in_record.is_multiple_of(10) {
            write!(file, "NS ")?;
        }
        if order[idx + 1] == 1 {
            boundary_segments += 1;
            let terminal = 1_isize - current as isize;
            writeln!(file, "{terminal} {boundary_segments}")?;
            position_in_record = 0;
        } else {
            write!(file, "{} ", current - 1)?;
            position_in_record += 1;
        }
    }

    Ok(boundary_segments)
}
